### PR TITLE
Pug instead Jade

### PR DESCRIPTION
**Pull request by fguisso**

### CODE REVIEW

**Comment by willianjusten** [comment]
The same I said in the other issue, I'm a little bit busy this week, but I'll try to see everything in the weekend ok =D

**Comment by grippado** [comment]
Hey @willianjusten, did you see this PR?
im wait you approve to use Qualy with pug =)

**Comment by willianjusten** [comment]
Hey sorry, I really forgot to take a look! So much time has passed and I forgot T.T
Will do right now, probably will need to update some packages after as well!

**Comment by willianjusten** [comment]
Everything working perfectly, thanks @fguisso and I'm really really sorry about this huge delay =/
@grippado after this merge, I'll update some stuff, as add the `.editorconfig`, fix some code style, new packages, if you could wait, I'll do it right now xD

**Pull request merged**
